import enum


class Privileges(enum.Enum):

    ADD_ALLERGIES = "Add Allergies"
    ADD_COHORTS = "Add Cohorts"
    ADD_COMMONLABTEST_METADATA = "Add CommonLabTest Metadata"
    ADD_COMMONLABTEST_ORDERS = "Add CommonLabTest Orders"
    ADD_COMMONLABTEST_RESULTS = "Add CommonLabTest Results"
    ADD_COMMONLABTEST_SAMPLES = "Add CommonLabTest Samples"
    ADD_CONCEPT_PROPOSALS = "Add Concept Proposals"
    ADD_ENCOUNTERS = "Add Encounters"
    ADD_FORMENTRY_ARCHIVE = "Add FormEntry Archive"
    ADD_FORMENTRY_ERROR = "Add FormEntry Error"
    ADD_FORMENTRY_QUEUE = "Add FormEntry Queue"
    ADD_HL7_INBOUND_ARCHIVE = "Add HL7 Inbound Archive"
    ADD_HL7_INBOUND_EXCEPTION = "Add HL7 Inbound Exception"
    ADD_HL7_INBOUND_QUEUE = "Add HL7 Inbound Queue"
    ADD_HL7_SOURCE = "Add HL7 Source"
    ADD_OBSERVATIONS = "Add Observations"
    ADD_ORDERS = "Add Orders"
    ADD_PATIENT_IDENTIFIERS = "Add Patient Identifiers"
    ADD_PATIENT_PROGRAMS = "Add Patient Programs"
    ADD_PATIENTS = "Add Patients"
    ADD_PEOPLE = "Add People"
    ADD_PROBLEMS = "Add Problems"
    ADD_RELATIONSHIPS = "Add Relationships"
    ADD_REPORT_OBJECTS = "Add Report Objects"
    ADD_REPORTS = "Add Reports"
    ADD_TEST_RESULT = "Add Test Result"
    ADD_USERS = "Add Users"
    ADD_VISITS = "Add Visits"
    ASSIGN_SYSTEM_DEVELOPER_ROLE = "Assign System Developer Role"
    CONFIGURE_VISITS = "Configure Visits"
    DELETE_COHORTS = "Delete Cohorts"
    DELETE_COMMONLABTEST_METADATA = "Delete CommonLabTest Metadata"
    DELETE_COMMONLABTEST_ORDERS = "Delete CommonLabTest Orders"
    DELETE_COMMONLABTEST_RESULTS = "Delete CommonLabTest Results"
    DELETE_COMMONLABTEST_SAMPLES = "Delete CommonLabTest Samples"
    DELETE_CONCEPT_PROPOSALS = "Delete Concept Proposals"
    DELETE_CONDITIONS = "Delete Conditions"
    DELETE_DIAGNOSES = "Delete Diagnoses"
    DELETE_ENCOUNTERS = "Delete Encounters"
    DELETE_FORMENTRY_ARCHIVE = "Delete FormEntry Archive"
    DELETE_FORMENTRY_ERROR = "Delete FormEntry Error"
    DELETE_FORMENTRY_QUEUE = "Delete FormEntry Queue"
    DELETE_HL7_INBOUND_ARCHIVE = "Delete HL7 Inbound Archive"
    DELETE_HL7_INBOUND_EXCEPTION = "Delete HL7 Inbound Exception"
    DELETE_HL7_INBOUND_QUEUE = "Delete HL7 Inbound Queue"
    DELETE_NOTES = "Delete Notes"
    DELETE_OBSERVATIONS = "Delete Observations"
    DELETE_ORDERS = "Delete Orders"
    DELETE_PATIENT_IDENTIFIERS = "Delete Patient Identifiers"
    DELETE_PATIENT_PROGRAMS = "Delete Patient Programs"

    VIEW_MDRTB_DATA = 'View MDR-TB Data'
    CREATE_MDRTB_DATA = 'Add MDR-TB Data'
    EDIT_PRIVILEGE_MDRTB_DATA = 'Edit MDR-TB Data'
    DELETE_PRIVILEGE_MDRTB_DATA = 'Delete MDR-TB Data'
